In [1]:
import sqlite3
import pandas as pd

In [4]:
df = pd.read_csv('final_merged_df.csv')

In [5]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delay_days,month,weekday,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,10,Monday,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,10,Monday,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,10,Monday,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,7,Tuesday,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,8,Wednesday,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,credit_card,3.0,179.12

In [6]:
conn = sqlite3.connect('ecommerce.db')

In [7]:
df.to_sql(
    'orders',
    conn,
    if_exists='replace',
    index=False
)

103887

In [8]:
query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""

pd.read_sql(query, conn)

   total_orders
0        103887

In [9]:
query = """
SELECT *
FROM orders
LIMIT 5;
"""

pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delay_days,month,weekday,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,10,Monday,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,10,Monday,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,10,Monday,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,7,Tuesday,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,8,Wednesday,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,credit_card,3.0,179.12

## Query 1: Total Number of Orders

Purpose: To find the total number of orders in the dataset.

In [10]:
query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""

pd.read_sql(query, conn)

   total_orders
0        103887

## Query 2: Delayed Orders

Purpose: To determine how many orders were delivered late.

In [11]:
query = """
SELECT COUNT(*) AS delayed_orders
FROM orders
WHERE delay_days > 0;
"""

pd.read_sql(query, conn)

   delayed_orders
0            6788

## Query 3: Average Delay Days

Purpose: To calculate the average delay in delivery.

In [12]:
query = """
SELECT AVG(delay_days) AS average_delay
FROM orders;
"""

pd.read_sql(query, conn)

   average_delay
0     -11.893623

## Query 4: Payment Method Distribution

**Purpose:** To determine the number of orders made using each payment method.

In [13]:
query = """
SELECT payment_type,
       COUNT(*) AS total_orders
FROM orders
GROUP BY payment_type;
"""

pd.read_sql(query, conn)

  payment_type  total_orders
0          NaN             1
1       boleto         19784
2  credit_card         76795
3   debit_card          1529
4  not_defined             3
5      voucher          5775

## Query 5: Top 10 Customer States

**Purpose:** To identify the states with the highest number of orders.

In [14]:
query = """
SELECT customer_state,
       COUNT(*) AS total_orders
FROM orders
GROUP BY customer_state
ORDER BY total_orders DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  customer_state  total_orders
0             SP         43623
1             RJ         13527
2             MG         12102
3             RS          5668
4             PR          5262
5             SC          3754
6             BA          3610
7             DF          2204
8             GO          2112
9             ES          2107

## Query 6: Average Delivery Days

**Purpose:** To calculate the average number of days taken for delivery.

In [15]:
query = """
SELECT AVG(delivery_days) AS avg_delivery_days
FROM orders;
"""

pd.read_sql(query, conn)

   avg_delivery_days
0          12.106764

## Query 7: Monthly Order Trend

**Purpose:** To analyze the number of orders placed each month.

In [17]:
query = """
SELECT month,
       COUNT(*) AS total_orders
FROM orders
GROUP BY month
ORDER BY month;
"""

pd.read_sql(query, conn)

    month  total_orders
0       1          8413
1       2          8838
2       3         10349
3       4          9780
4       5         11079
5       6          9855
6       7         10824
7       8         11248
8       9          4536
9      10          5206
10     11          7863
11     12          5896

## Query 8: States with More Than 1000 Orders

**Purpose:** To find states with a high concentration of orders.

In [18]:
query = """
SELECT customer_state,
       COUNT(*) AS total_orders
FROM orders
GROUP BY customer_state
HAVING COUNT(*) > 1000;
"""

pd.read_sql(query, conn)

   customer_state  total_orders
0              BA          3610
1              CE          1398
2              DF          2204
3              ES          2107
4              GO          2112
5              MG         12102
6              PA          1011
7              PE          1728
8              PR          5262
9              RJ         13527
10             RS          5668
11             SC          3754
12             SP         43623

## Query 9: Maximum Delay

**Purpose:** To identify the highest delivery delay recorded.

In [19]:
query = """
SELECT MAX(delay_days) AS max_delay
FROM orders;
"""

pd.read_sql(query, conn)

   max_delay
0      188.0

## Query 10: Top 5 Payment Methods

**Purpose:** To determine the five most frequently used payment methods.

In [20]:
query = """
SELECT payment_type,
       COUNT(*) AS total_orders
FROM orders
GROUP BY payment_type
ORDER BY total_orders DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

  payment_type  total_orders
0  credit_card         76795
1       boleto         19784
2      voucher          5775
3   debit_card          1529
4  not_defined             3

In [21]:
conn.close()